spring.application.name=iw_order_service
server.port=8082

spring.config.import=classpath:private/private_application.properties
spring.datasource.url=jdbc:postgresql://${db.url}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}

spring.liquibase.enabled=true

service.userservice.url=http://localhost:8081

spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.registration.keycloak.client-id=${keycloak.client-id}
spring.security.oauth2.client.registration.keycloak.client-secret=${keycloak.client-secret}
spring.security.oauth2.client.registration.keycloak.client-name=${keycloak.client-name}
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid, profile, email
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/iw_payment_app

spring.security.oauth2.client.provider.keycloak.token-uri=http://localhost:8080/realms/iw_payment_app/protocol/openid-connect/token
