spring.application.name=iw_order_service
server.port=8082

spring.config.import=classpath:private/private_application.properties
spring.datasource.url=jdbc:postgresql://${db.url}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}

spring.liquibase.enabled=true